version = 1

test_patterns = [
  "tests/**"
]

exclude_patterns = [
  "examples/**",
  "docs/**"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "docker"
enabled = true
