
image:
    file: scripts/gitpod.Dockerfile
tasks:
  - init: >
      rm $(pyenv prefix)/lib/libpython* &&
      pip install -U pip setuptools wheel &&
      pip install -e .[dev] &&
      pip install cython &&
      dffml service dev install &&
      echo -e '#!/bin/sh\nexec python3 -m black --check .' > .git/hooks/pre-commit &&
      chmod 755 .git/hooks/pre-commit

vscode:
  extensions:
    - ms-python.python
