image:
    file: scripts/gitpod.Dockerfile
tasks:
  - init: >
      pip install -U pip &&
      pip install -e .[dev] &&
      rm $(pyenv prefix)/lib/libpython* &&
      dffml service dev install &&
      echo -e '#!/bin/sh\nexec python3 -m black --check .' > .git/hooks/pre-commit &&
      chmod 755 .git/hooks/pre-commit
