queries:
  - exclude: py/call/wrong-number-class-arguments
path_classifiers:
  docs:
    - scripts/docs.py
  test:
    - tests
extraction:
  python:
    python_setup:
      setup_py: setup.py
      version: 3
    index:
      include:
       - "dffml/**"
       - "examples/**"
       - "model/**"
       - "source/**"
       - "service/**"
       - "configloader/**"
       - "operations/**"
       - "feature/**"
