definitions:
  git_repository_checked_out:
    lock: true
    name: git_repository_checked_out
    primitive: Dict[str, str]
    spec:
      defaults:
        URL: null
        commit: null
      name: GitRepoCheckedOutSpec
      types:
        URL: str
        commit: str
        directory: str
    subspec: false
  key:
    name: key
    primitive: str
  language_to_comment_ratio:
    name: language_to_comment_ratio
    primitive: int
  lines_by_language_count:
    name: lines_by_language_count
    primitive: Dict[str, Dict[str, int]]
  mapping:
    name: mapping
    primitive: map
  value:
    name: value
    primitive: generic
flow:
  dffml.mapping.create:
    inputs:
      key:
      - seed
      value:
      - pypi_package_contents: directory
  lines_of_code_by_language:
    inputs:
      repo:
      - dffml.mapping.create: mapping
  lines_of_code_to_comments:
    inputs:
      langs:
      - lines_of_code_by_language: lines_by_language
linked: true
operations:
  dffml.mapping.create:
    inputs:
      key: key
      value: value
    name: dffml.mapping.create
    outputs:
      mapping: mapping
    stage: processing
  lines_of_code_by_language:
    inputs:
      repo: git_repository_checked_out
    name: lines_of_code_by_language
    outputs:
      lines_by_language: lines_by_language_count
    stage: processing
  lines_of_code_to_comments:
    inputs:
      langs: lines_by_language_count
    name: lines_of_code_to_comments
    outputs:
      code_to_comment_ratio: language_to_comment_ratio
    stage: processing
seed:
- definition: key
  value: directory
- definition: get_single_spec
  value:
  - safety_check.outputs.result
  - run_bandit.outputs.result
  - language_to_comment_ratio

