dffml accuracy \
  -model ner_tagger \
  -model-predict TARGET:float:1 \
  -sources s=csv \
  -source-filename train.csv \
  -model-SENTENCE_ID SentenceId:int:1 \
  -model-WORDS Words:str:1 \
  -model-predict Tag:str:1 \
  -model-model_architecture_type bert \
  -model-model_name_or_path bert-base-cased \
  -model-no_cuda \
  -log debug