version: "3"

networks:
  alice_forgejo_network:
    external: false
  bob_forgejo_network:
    external: false

services:
  alice_forgejo_server:
    image: codeberg.org/forgejo/forgejo:1.19.0-2-rootless
    container_name: alice_forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - alice_forgejo_network
    volumes:
      - ./alice_forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "2000:3000"
      - "2022:2222"

  bob_forgejo_server:
    image: codeberg.org/forgejo/forgejo:1.19.0-2-rootless
    container_name: bob_forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - bob_forgejo_network
    volumes:
      - ./bob_forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "3022:2222"
