name: "00 PR Auto approve"

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: contains(fromJson('["dependabot[bot]", "github-actions[bot]", "pdxjohnny"]'), github.actor)
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          review-message: "LGTM"
