name: Delpoy

on: [push, pull_request]

jobs:
  do:
    name: Digital Ocean
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    env:
      PYTHON_VERSION: 3.7

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: $PYTHON_VERSION
    - name: Get pip cache
      id: pip-cache
      run: |
        python -c "from pip._internal.locations import USER_CACHE_DIR; print('::set-output name=dir::' + USER_CACHE_DIR)"
    - name: pip cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        python -m pip install -U setuptools wheel
        python -m pip install -r requirements.txt
    - name: Run deployment script
      run: |
        export DIGITALOCEAN_ACCESS_TOKEN=${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        export DO_SSH_KEY_NAME=${{ secrets.DO_SSH_KEY_NAME }}
        export DO_SSH_KEY_PASSWORD=${{ secrets.DO_SSH_KEY_PASSWORD }}
        export DO_SSH_KEY_PRIVATE=${{ secrets.DO_SSH_KEY_PRIVATE }}
        export DO_SSH_KEY_PUBLIC=${{ secrets.DO_SSH_KEY_PUBLIC }}
        export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        python infra/do.py
